# Generated by Django 5.2 on 2025-04-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_adoptiondemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptiondemand',
            name='experience',
            field=models.TextField(blank=True, help_text='Describe your experience with pets'),
        ),
        migrations.AddField(
            model_name='adoptiondemand',
            name='living_arrangement',
            field=models.CharField(blank=True, help_text='Where will the pet live (apartment, house with yard, etc.)?', max_length=200),
        ),
        migrations.AddField(
            model_name='adoptiondemand',
            name='motivation_letter',
            field=models.TextField(blank=True, help_text='Why do you want to adopt this pet?'),
        ),
        migrations.AddField(
            model_name='adoptiondemand',
            name='past_ownership',
            field=models.BooleanField(default=False, help_text='Have you owned pets before?'),
        ),
    ]
